create table if not exists public.connection_tests (
  id bigint generated by default as identity primary key,
  title text not null,
  status text not null default 'ok',
  created_at timestamptz not null default now()
);

insert into public.connection_tests (title, status)
values
  ('Supabase Verbindung steht', 'ok'),
  ('Next.js kann Daten lesen', 'ok')
on conflict do nothing;

alter table public.connection_tests enable row level security;

drop policy if exists "Allow public read access for connection tests"
on public.connection_tests;

create policy "Allow public read access for connection tests"
on public.connection_tests
for select
to anon
using (true);
